name = "Sunny"
uuid = "2b4a2ac8-8f8b-43e8-abf4-3cb0c45e8736"
authors = ["The Sunny team"]
version = "0.5.10"

[deps]
CrystalInfoFramework = "6007d9b0-c6b2-11e8-0510-1d10e825f3f1"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Spglib = "f761d5c5-86db-4880-b97f-9680a7cccfb5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[extensions]
ExportVTKExt = "WriteVTK"
GLMakiePrecompilesExt = "GLMakie"
PlottingExt = "Makie"
WGLMakiePrecompilesExt = "WGLMakie"

[compat]
CrystalInfoFramework = "0.6.0"
DataStructures = "0.18.13"
DynamicPolynomials = "0.5.2"
FFTW = "1.4.5"
FilePathsBase = "0.9.18"
GLMakie = "0.9, 0.10"
HCubature = "1.5.1"
JLD2 = "0.4.33"
LinearAlgebra = "1.9"
LinearMaps = "3.11.0"
Makie = "0.20, 0.21.1"
OffsetArrays = "1.10.8"
Optim = "1.7.6"
PrecompileTools = "1.2.0"
Printf = "1.9"
Random = "1.9"
RowEchelon = "0.2.1"
SpecialFunctions = "2.1.0"
Spglib = "0.9.4"
StaticArrays = "1.9.1"
WGLMakie = "0.9, 0.10"
WriteVTK = "1.18.0"
julia = "1.9"
