name = "Sunny"
uuid = "2b4a2ac8-8f8b-43e8-abf4-3cb0c45e8736"
authors = ["The Sunny team"]
version = "0.7.9"

[deps]
Brillouin = "23470ee3-d0df-4052-8b1a-8cbd6363e7f0"
CrystalInfoFramework = "6007d9b0-c6b2-11e8-0510-1d10e825f3f1"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Spglib = "f761d5c5-86db-4880-b97f-9680a7cccfb5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[extensions]
ExportVTKExt = "WriteVTK"
GLMakiePrecompilesExt = ["Makie", "GLMakie"]
PlottingExt = "Makie"
WGLMakiePrecompilesExt = ["Makie", "WGLMakie"]

[compat]
Brillouin = "0.5.19"
CrystalInfoFramework = "0.8, 1"
DynamicPolynomials = "0.6.0"
ElasticArrays = "1.2.12"
FFTW = "1.4.5"
GLMakie = "0.13"
HCubature = "1.7.0"
JLD2 = "0.5.4, 0.6"
LinearAlgebra = "1.10"
Makie = "0.24"
OffsetArrays = "1.10.8"
Optim = "1.13.0"
PrecompileTools = "1.2.0"
Printf = "1.10"
Random = "1.10"
RowEchelon = "0.2.1"
SpecialFunctions = "2.1.0"
Spglib = "0.9.4"
StaticArrays = "1.9.1"
Statistics = "1.10"
WGLMakie = "0.13"
WriteVTK = "1.18.0"
julia = "1.10"
