[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Sunny = "2b4a2ac8-8f8b-43e8-abf4-3cb0c45e8736"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"
